services:
  directional-scalper:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/code/
    working_dir: /code
    command: python3 bot.py --mode hedge --symbol GALAUSDT --iqty 1 --tg off
    
